# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u0418\u043c\u044f')),
                ('identifier', models.IntegerField(unique=True, verbose_name='ID')),
                ('mac', models.CharField(blank=True, max_length=12, null=True, verbose_name='MAC-\u0430\u0434\u0440\u0435\u0441')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-\u0430\u0434\u0440\u0435\u0441')),
                ('is_online', models.BooleanField(default=False, verbose_name='\u0412 \u0441\u0435\u0442\u0438')),
                ('last_online', models.DateTimeField(blank=True, null=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u043f\u043e\u0441\u043b\u0435\u0434\u043d\u0435\u0439 \u0441\u0432\u044f\u0437\u0438')),
            ],
            options={
                'verbose_name': '\u0423\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u043e',
                'verbose_name_plural': '\u0423\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0430',
            },
        ),
    ]
