# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-24 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataflow', '0003_auto_20160824_0620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received', models.DateTimeField(auto_now=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u0438\u044f')),
                ('data', models.TextField(verbose_name='\u0421\u043e\u0434\u0435\u0440\u0436\u0438\u043c\u043e\u0435')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataflow.Device')),
            ],
            options={
                'verbose_name': '\u041f\u0430\u043a\u0435\u0442',
                'verbose_name_plural': '\u041f\u0430\u043a\u0435\u0442\u044b',
            },
        ),
        migrations.AlterModelOptions(
            name='debugpacket',
            options={'verbose_name': '\u041e\u0442\u043b. \u041f\u0430\u043a\u0435\u0442', 'verbose_name_plural': '\u041e\u0442\u043b. \u041f\u0430\u043a\u0435\u0442\u044b'},
        ),
    ]
