# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-24 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataflow', '0004_auto_20160824_0648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.DateTimeField(blank=True, null=True, verbose_name='\u0417\u0430\u043f\u043b\u0430\u043d\u0438\u0440\u043e\u0432\u0430\u0442\u044c \u043d\u0430 \u0432\u0440\u0435\u043c\u044f')),
                ('do_on_connect', models.BooleanField(default=False, verbose_name='\u0412\u044b\u043f\u043e\u043b\u043d\u0438\u0442\u044c \u043f\u0440\u0438 \u043f\u043e\u044f\u0432\u043b\u0435\u043d\u0438\u0438 \u0432 \u0441\u0435\u0442\u0438')),
                ('is_done', models.BooleanField(default=False, verbose_name='\u0412\u044b\u043f\u043e\u043b\u043d\u0435\u043d\u0430')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataflow.Device')),
            ],
            options={
                'verbose_name': '\u041a\u043e\u043c\u0430\u043d\u0434\u044b',
                'verbose_name_plural': '\u041a\u043e\u043c\u0430\u043d\u0434\u044b',
            },
        ),
        migrations.CreateModel(
            name='CommandTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('conf', models.TextField(blank=True, null=True, verbose_name='\u041a\u043e\u043d\u0444\u0438\u0433\u0443\u0440\u0430\u0446\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u0428\u0430\u0431\u043b\u043e\u043d \u043a\u043e\u043c\u0430\u043d\u0434\u044b',
                'verbose_name_plural': '\u0428\u0430\u0431\u043b\u043e\u043d\u044b \u043a\u043e\u043c\u0430\u043d\u0434',
            },
        ),
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0413\u0440\u0443\u043f\u043f\u0430 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432',
                'verbose_name_plural': '\u0413\u0440\u0443\u043f\u043f\u044b \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('conf', models.TextField(blank=True, null=True, verbose_name='\u041a\u043e\u043d\u0444\u0438\u0433\u0443\u0440\u0430\u0446\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u0422\u0438\u043f \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0430',
                'verbose_name_plural': '\u0422\u0438\u043f\u044b \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('received', models.DateTimeField(auto_now=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u044f')),
                ('data', models.TextField(verbose_name='\u0414\u0430\u043d\u043d\u044b\u0435')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataflow.Device')),
            ],
            options={
                'verbose_name': '\u0414\u0430\u0442\u0447\u0438\u043a',
                'verbose_name_plural': '\u0414\u0430\u0442\u0447\u0438\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('conf', models.TextField(blank=True, null=True, verbose_name='\u041a\u043e\u043d\u0444\u0438\u0433\u0443\u0440\u0430\u0446\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u0422\u0438\u043f \u0441\u0435\u043d\u0441\u043e\u0440\u0430',
                'verbose_name_plural': '\u0422\u0438\u043f\u044b \u0441\u0435\u043d\u0441\u043e\u0440\u043e\u0432',
            },
        ),
        migrations.AlterModelOptions(
            name='debugpacket',
            options={'verbose_name': '\u0414\u0435\u0431\u0430\u0433', 'verbose_name_plural': '\u0414\u0435\u0431\u0430\u0433'},
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataflow.SensorType'),
        ),
        migrations.AddField(
            model_name='command',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataflow.CommandTemplate'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataflow.DeviceGroup'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataflow.DeviceType'),
        ),
    ]
