# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataflow', '0005_auto_20160824_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='port',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u041f\u043e\u0440\u0442'),
        ),
    ]
