# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-04 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataflow', '0006_device_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.DateTimeField(blank=True, null=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u0432\u044b\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u044f')),
                ('result', models.TextField(blank=True, null=True, verbose_name='\u0420\u0435\u0437\u0443\u043b\u044c\u0442\u0430\u0442')),
            ],
            options={
                'verbose_name': '\u0412\u044b\u043f\u043e\u043b\u043d\u0435\u043d\u043d\u0430\u044f \u043a\u043e\u043c\u0430\u043d\u0434\u0430',
                'verbose_name_plural': '\u0412\u044b\u043f\u043e\u043b\u043d\u0435\u043d\u043d\u044b\u0435 \u043a\u043e\u043c\u0430\u043d\u0434\u044b',
            },
        ),
        migrations.RemoveField(
            model_name='command',
            name='is_done',
        ),
        migrations.AlterField(
            model_name='command',
            name='do_on_connect',
            field=models.BooleanField(default=False, verbose_name='\u0412\u044b\u043f\u043e\u043b\u043d\u044f\u0442\u044c \u043f\u0440\u0438 \u043f\u043e\u044f\u0432\u043b\u0435\u043d\u0438\u0438 \u0432 \u0441\u0435\u0442\u0438'),
        ),
        migrations.AddField(
            model_name='commandhistory',
            name='command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataflow.Command'),
        ),
    ]
