# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-04 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataflow', '0007_auto_20160904_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='dataflow.Device'),
        ),
    ]
