# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-04 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataflow', '0008_auto_20160904_0521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='command',
            options={'ordering': ['order'], 'verbose_name': '\u041a\u043e\u043c\u0430\u043d\u0434\u044b', 'verbose_name_plural': '\u041a\u043e\u043c\u0430\u043d\u0434\u044b'},
        ),
        migrations.AddField(
            model_name='command',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u041f\u043e\u0440\u044f\u0434\u043e\u043a \u0432\u044b\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u044f'),
        ),
    ]
