# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 00:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dataflow', '0009_auto_20160904_0530'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u0432\u044b\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u044f')),
                ('result', models.TextField(blank=True, null=True, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435 \u0441\u0435\u043d\u0441\u043e\u0440\u0430',
                'verbose_name_plural': '\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u044f \u0441\u0435\u043d\u0441\u043e\u0440\u043e\u0432',
            },
        ),
        migrations.RemoveField(
            model_name='message',
            name='device',
        ),
        migrations.RemoveField(
            model_name='command',
            name='do_on_connect',
        ),
        migrations.RemoveField(
            model_name='command',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='commandhistory',
            name='done',
        ),
        migrations.RemoveField(
            model_name='commandtemplate',
            name='conf',
        ),
        migrations.RemoveField(
            model_name='devicetype',
            name='conf',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='data',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='received',
        ),
        migrations.RemoveField(
            model_name='sensortype',
            name='conf',
        ),
        migrations.AddField(
            model_name='command',
            name='compare_type',
            field=models.IntegerField(choices=[(1, '\u0420\u0430\u0432\u043d\u043e'), (2, '\u041d\u0435 \u0440\u0430\u0432\u043d\u043e'), (3, '\u0411\u043e\u043b\u044c\u0448\u0435'), (5, '\u0411\u043e\u043b\u044c\u0448\u0435 \u043b\u0438\u0431\u043e \u0440\u0430\u0432\u043d\u043e'), (4, '\u041c\u0435\u043d\u044c\u0448\u0435'), (6, '\u041c\u0435\u043d\u044c\u0448\u0435 \u043b\u0438\u0431\u043e \u0440\u0430\u0432\u043d\u043e')], default=1, verbose_name='\u0421\u0440\u0430\u0432\u043d\u0435\u043d\u0438\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u044f \u0441\u0435\u043d\u0441\u043e\u0440\u0430'),
        ),
        migrations.AddField(
            model_name='command',
            name='cron',
            field=models.TextField(blank=True, help_text='\u041a\u0430\u043a \u0432 crontab, @reboot \u043d\u0435 \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u0435\u0442\u0441\u044f', null=True, verbose_name='\u041f\u0435\u0440\u0438\u043e\u0434\u0438\u0447\u043d\u043e\u0441\u0442\u044c'),
        ),
        migrations.AddField(
            model_name='command',
            name='exec_count',
            field=models.IntegerField(default=0, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0432\u044b\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u0439'),
        ),
        migrations.AddField(
            model_name='command',
            name='exec_type',
            field=models.IntegerField(choices=[(1, '\u041f\u0440\u0438 \u043f\u043e\u044f\u0432\u043b\u0435\u043d\u0438\u0438 \u0432 \u0441\u0435\u0442\u0438'), (2, '\u041f\u043e cron'), (3, '\u041f\u043e \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u044e \u0441\u0435\u043d\u0441\u043e\u0440\u0430'), (4, '\u041d\u0435\u0437\u0430\u043c\u0435\u0434\u043b\u0438\u0442\u0435\u043b\u044c\u043d\u043e')], default=4, verbose_name='\u0422\u0440\u0438\u0433\u0433\u0435\u0440 \u0432\u044b\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='command',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='dataflow.Sensor'),
        ),
        migrations.AddField(
            model_name='commandhistory',
            name='time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 9, 5, 0, 27, 54, 46342, tzinfo=utc), verbose_name='\u0412\u0440\u0435\u043c\u044f \u0432\u044b\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u044f'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commandtemplate',
            name='script',
            field=models.TextField(blank=True, null=True, verbose_name='\u0421\u043a\u0440\u0438\u043f\u0442'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='script',
            field=models.TextField(blank=True, help_text='\u041f\u043e\u043b\u0435 \u0432 \u0434\u0430\u043d\u043d\u043e\u0435 \u0432\u0440\u0435\u043c\u044f \u043d\u0438\u043a\u0430\u043a \u043d\u0435 \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u0435\u0442\u0441\u044f', null=True, verbose_name='\u0421\u043a\u0440\u0438\u043f\u0442 \u0437\u0430\u043f\u0443\u0441\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='identifier',
            field=models.IntegerField(default=1, help_text='\u0418\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u0435\u0442\u0441\u044f \u0434\u043b\u044f \u0438\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0446\u0438\u0438 DAT-\u043f\u0430\u043a\u0435\u0442\u0430, \u0434\u0443\u0431\u043b\u0438\u0440\u0443\u0435\u0442\u0441\u044f \u0432 \u043f\u0440\u0435\u0434\u0435\u043b\u0430\u0445 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0430', verbose_name='ID \u0441\u0435\u043d\u0441\u043e\u0440\u0430'),
        ),
        migrations.AddField(
            model_name='sensortype',
            name='length',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0414\u043b\u0438\u043d\u0430'),
        ),
        migrations.AddField(
            model_name='sensortype',
            name='start',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0421\u0442\u0430\u0440\u0442\u043e\u0432\u044b\u0439 \u0431\u0430\u0439\u0442'),
        ),
        migrations.AddField(
            model_name='sensortype',
            name='template',
            field=models.CharField(default=1, max_length=255, verbose_name='STRUCT-\u0448\u0430\u0431\u043b\u043e\u043d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensortype',
            name='unit',
            field=models.CharField(default='', max_length=255, verbose_name='\u0415\u0434\u0438\u043d\u0438\u0446\u0430 \u0438\u0437\u043c\u0435\u0440\u0435\u043d\u0438\u044f'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commandhistory',
            name='result',
            field=models.CharField(blank=True, max_length=4095, null=True, verbose_name='\u0420\u0435\u0437\u0443\u043b\u044c\u0442\u0430\u0442'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='dataflow.Device'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AddField(
            model_name='sensorhistory',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataflow.Sensor'),
        ),
    ]
