# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataflow', '0010_auto_20160905_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandhistory',
            name='succeed',
            field=models.BooleanField(default=False, verbose_name='\u0423\u0441\u043f\u0435\u0448\u043d\u043e'),
        ),
    ]
