# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataflow', '0011_commandhistory_succeed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commandhistory',
            old_name='succeed',
            new_name='success',
        ),
        migrations.AddField(
            model_name='commandhistory',
            name='error_message',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0421\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435 \u043e\u0431 \u043e\u0448\u0438\u0431\u043a\u0435'),
        ),
    ]
