# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataflow', '0012_auto_20160905_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandhistory',
            name='result',
            field=models.TextField(blank=True, max_length=4095, null=True, verbose_name='\u0420\u0435\u0437\u0443\u043b\u044c\u0442\u0430\u0442'),
        ),
    ]
