# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-06 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataflow', '0013_auto_20160906_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debugpacket',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataflow.Device'),
        ),
    ]
