# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-06 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataflow', '0014_auto_20160906_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='debugpacket',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-\u0430\u0434\u0440\u0435\u0441'),
        ),
        migrations.AddField(
            model_name='debugpacket',
            name='port',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u041f\u043e\u0440\u0442'),
        ),
    ]
