# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-06 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataflow', '0015_auto_20160906_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='debugpacket',
            name='protocol',
            field=models.IntegerField(blank=True, choices=[(1, 'TCP'), (2, 'UDP')], default=None, null=True, verbose_name='\u041f\u0440\u043e\u0442\u043e\u043a\u043e\u043b'),
        ),
    ]
