# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-06 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataflow', '0017_debugpacket_prefix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor',
            options={'verbose_name': '\u0421\u0435\u043d\u0441\u043e\u0440', 'verbose_name_plural': '\u0421\u0435\u043d\u0441\u043e\u0440\u044b'},
        ),
    ]
